require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe OutputIndicatorsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # OutputIndicator. As you add validations to OutputIndicator, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OutputIndicatorsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all output_indicators as @output_indicators" do
      output_indicator = OutputIndicator.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:output_indicators)).to eq([output_indicator])
    end
  end

  describe "GET #show" do
    it "assigns the requested output_indicator as @output_indicator" do
      output_indicator = OutputIndicator.create! valid_attributes
      get :show, {:id => output_indicator.to_param}, valid_session
      expect(assigns(:output_indicator)).to eq(output_indicator)
    end
  end

  describe "GET #new" do
    it "assigns a new output_indicator as @output_indicator" do
      get :new, {}, valid_session
      expect(assigns(:output_indicator)).to be_a_new(OutputIndicator)
    end
  end

  describe "GET #edit" do
    it "assigns the requested output_indicator as @output_indicator" do
      output_indicator = OutputIndicator.create! valid_attributes
      get :edit, {:id => output_indicator.to_param}, valid_session
      expect(assigns(:output_indicator)).to eq(output_indicator)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new OutputIndicator" do
        expect {
          post :create, {:output_indicator => valid_attributes}, valid_session
        }.to change(OutputIndicator, :count).by(1)
      end

      it "assigns a newly created output_indicator as @output_indicator" do
        post :create, {:output_indicator => valid_attributes}, valid_session
        expect(assigns(:output_indicator)).to be_a(OutputIndicator)
        expect(assigns(:output_indicator)).to be_persisted
      end

      it "redirects to the created output_indicator" do
        post :create, {:output_indicator => valid_attributes}, valid_session
        expect(response).to redirect_to(OutputIndicator.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved output_indicator as @output_indicator" do
        post :create, {:output_indicator => invalid_attributes}, valid_session
        expect(assigns(:output_indicator)).to be_a_new(OutputIndicator)
      end

      it "re-renders the 'new' template" do
        post :create, {:output_indicator => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested output_indicator" do
        output_indicator = OutputIndicator.create! valid_attributes
        put :update, {:id => output_indicator.to_param, :output_indicator => new_attributes}, valid_session
        output_indicator.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested output_indicator as @output_indicator" do
        output_indicator = OutputIndicator.create! valid_attributes
        put :update, {:id => output_indicator.to_param, :output_indicator => valid_attributes}, valid_session
        expect(assigns(:output_indicator)).to eq(output_indicator)
      end

      it "redirects to the output_indicator" do
        output_indicator = OutputIndicator.create! valid_attributes
        put :update, {:id => output_indicator.to_param, :output_indicator => valid_attributes}, valid_session
        expect(response).to redirect_to(output_indicator)
      end
    end

    context "with invalid params" do
      it "assigns the output_indicator as @output_indicator" do
        output_indicator = OutputIndicator.create! valid_attributes
        put :update, {:id => output_indicator.to_param, :output_indicator => invalid_attributes}, valid_session
        expect(assigns(:output_indicator)).to eq(output_indicator)
      end

      it "re-renders the 'edit' template" do
        output_indicator = OutputIndicator.create! valid_attributes
        put :update, {:id => output_indicator.to_param, :output_indicator => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested output_indicator" do
      output_indicator = OutputIndicator.create! valid_attributes
      expect {
        delete :destroy, {:id => output_indicator.to_param}, valid_session
      }.to change(OutputIndicator, :count).by(-1)
    end

    it "redirects to the output_indicators list" do
      output_indicator = OutputIndicator.create! valid_attributes
      delete :destroy, {:id => output_indicator.to_param}, valid_session
      expect(response).to redirect_to(output_indicators_url)
    end
  end

end
