require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe TypeorgsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Typeorg. As you add validations to Typeorg, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TypeorgsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all typeorgs as @typeorgs" do
      typeorg = Typeorg.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:typeorgs)).to eq([typeorg])
    end
  end

  describe "GET #show" do
    it "assigns the requested typeorg as @typeorg" do
      typeorg = Typeorg.create! valid_attributes
      get :show, {:id => typeorg.to_param}, valid_session
      expect(assigns(:typeorg)).to eq(typeorg)
    end
  end

  describe "GET #new" do
    it "assigns a new typeorg as @typeorg" do
      get :new, {}, valid_session
      expect(assigns(:typeorg)).to be_a_new(Typeorg)
    end
  end

  describe "GET #edit" do
    it "assigns the requested typeorg as @typeorg" do
      typeorg = Typeorg.create! valid_attributes
      get :edit, {:id => typeorg.to_param}, valid_session
      expect(assigns(:typeorg)).to eq(typeorg)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Typeorg" do
        expect {
          post :create, {:typeorg => valid_attributes}, valid_session
        }.to change(Typeorg, :count).by(1)
      end

      it "assigns a newly created typeorg as @typeorg" do
        post :create, {:typeorg => valid_attributes}, valid_session
        expect(assigns(:typeorg)).to be_a(Typeorg)
        expect(assigns(:typeorg)).to be_persisted
      end

      it "redirects to the created typeorg" do
        post :create, {:typeorg => valid_attributes}, valid_session
        expect(response).to redirect_to(Typeorg.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved typeorg as @typeorg" do
        post :create, {:typeorg => invalid_attributes}, valid_session
        expect(assigns(:typeorg)).to be_a_new(Typeorg)
      end

      it "re-renders the 'new' template" do
        post :create, {:typeorg => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested typeorg" do
        typeorg = Typeorg.create! valid_attributes
        put :update, {:id => typeorg.to_param, :typeorg => new_attributes}, valid_session
        typeorg.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested typeorg as @typeorg" do
        typeorg = Typeorg.create! valid_attributes
        put :update, {:id => typeorg.to_param, :typeorg => valid_attributes}, valid_session
        expect(assigns(:typeorg)).to eq(typeorg)
      end

      it "redirects to the typeorg" do
        typeorg = Typeorg.create! valid_attributes
        put :update, {:id => typeorg.to_param, :typeorg => valid_attributes}, valid_session
        expect(response).to redirect_to(typeorg)
      end
    end

    context "with invalid params" do
      it "assigns the typeorg as @typeorg" do
        typeorg = Typeorg.create! valid_attributes
        put :update, {:id => typeorg.to_param, :typeorg => invalid_attributes}, valid_session
        expect(assigns(:typeorg)).to eq(typeorg)
      end

      it "re-renders the 'edit' template" do
        typeorg = Typeorg.create! valid_attributes
        put :update, {:id => typeorg.to_param, :typeorg => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested typeorg" do
      typeorg = Typeorg.create! valid_attributes
      expect {
        delete :destroy, {:id => typeorg.to_param}, valid_session
      }.to change(Typeorg, :count).by(-1)
    end

    it "redirects to the typeorgs list" do
      typeorg = Typeorg.create! valid_attributes
      delete :destroy, {:id => typeorg.to_param}, valid_session
      expect(response).to redirect_to(typeorgs_url)
    end
  end

end
